exp_name: "inference_only-angular_refusal_greedy-'@{model.name}'"

model:
  do_sample: False
  temperature: 1.0
  refusal_dir_path: ""   # compute 8-pair direction on-the-fly

method:
  name: angular_refusal_greedy
  method_class: angular_steering

  mode: refusal_only
  target_degree: 180.0
  adaptive: False
  num_features: 8
  neuronpedia_api_key: ""
