exp_name: "inference_only-angular_refusal_180_toolsdir_prehook-'@{model.name}'"

model:
  layer: 15
  do_sample: False
  temperature: 1.0
  refusal_dir_path: "tools/refusal_direction/pipeline/runs/gemma-2-2b-it/direction.pt"

method:
  name: angular_refusal_180_toolsdir_prehook
  method_class: angular_steering

  mode: refusal_only
  target_degree: 180.0
  adaptive: False
  use_pre_hook: True
  num_features: 8
  neuronpedia_api_key: ""
